apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc-claim-1
  labels:
    app: wordpress-1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
