apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-efs-pv-2
  labels:
    app: wordpress-1
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/ec2-user/eks-volume1"
