apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: QWRtaW5BZG1pbg==
  privateKey: YjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNBQUdmRm40cDJyT3o5L1UzekUvOFN0MkV4VDVSMXh2SzFSR3YrQ0ppWVBzZ0FBQUppZ3NWWElvTEZWCnlBQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQUFHZkZuNHAyck96OS9VM3pFLzhTdDJFeFQ1UjF4dksxUkd2K0NKaVlQc2cKQUFBRUF0V2N0aE5YWDhZcVMxczJRQXZOWDVCOEU3bnR4M1VkQTB4Mnp6SkdKYXlRQVo4V2ZpbmFzN1AzOVRmTVQveEszWQpURlBsSFhHOHJWRWEvNEltSmcreUFBQUFFM0JwYm10bGMyaEFZMnh2ZFdSbGNTNWpiMjBCQWc9PQ==
