apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: wordpress
  annotations:
    external-dns.alpha.kubernetes.io/hostname: eks1.ceqapp.com    
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol | default "TCP" }}
  selector:
    app: wordpress
    tier: frontend
  type: {{ .Values.service.type }}
